#!/bin/sh

dep_ch() {
    for dep; do
        command -v "${dep%% *}" >/dev/null || die "Program \"${dep%% *}\" not found. Please install it."
    done
}

get_schedule() {
    today=$(date --date="-1 week + $1 days" '+%Y-%m-%d')
    this_year=$(date --date="-1 week + $1 days" '+%Y')
    this_week=$(date --date="-1 week + $1 days" '+%V')
    curr_time=$(date '+%H:%M')
    anisch_token="8oIOXRjBWyoDVdeIWhFkk4D7Clc5z9"
    animeschedule="https://animeschedule.net"
    printf "\033[96;1;4m\0Schedule for $(date --date="-1 week + $1 days" "+%A %e %B"):\033[0m\n"
    last_time=""
    curl -s -H "Authorization: Bearer $anisch_token" \
        "$animeschedule/api/v3/timetables/sub?year=$this_year&week=$this_week" \
        | sed 's|"title"|\n|g' | \
    while read -r anime; do
        #echo $anime
        if [ $today != $(echo $anime | sed -E 's|.*"episodeDate":"([^T]*)T.*|\1|1') ]; then
            continue
        fi
        ani_route=$(echo $anime | sed -nE 's|^:"[^"]*"*,"route":"([^"]*)".*|\1|p')
        ep_time=$(echo $anime \
            | sed -E 's|.*"episodeDate":"[^T]*T([^Z]*):[^:Z]*Z.*|\1|1')
        if [[ ! -z $last_time && $ep_time = $last_time ]]; then
            printf "\033[1m-------------\033[0m\n"
        else
            printf "\n\033[1m--- \033[%sm%s\033[39m ---\033[0m\n" \
                $(if [ $1 -gt 7 -o $curr_time \< $ep_time -a $1 -ge 7 ]; then
                    echo 33; else echo 32
                fi) \
                $ep_time
        fi
        mal_link=$(curl -s -H "Authorization: Bearer $anisch_token" \
            $animeschedule/api/v3/anime/$ani_route \
            | sed -nE 's|.*"websites":\{.*"mal":"([^"]*)".*|\1|p')
        echo -e "\033[1mTitle:\033[0m \033]8;;https://$mal_link\e\\$(echo $anime \
            | sed -nE 's|^:"([^"]*)",.*|\1|p')\033]8;;\033\\"
        english_title=$(echo $anime \
            | sed -nE 's|.*,"english":"([^"]*)",.*|\1|p')
        if [[ ! -z $english_title ]]; then
            echo -e "\033[1mEnglish Title:\033[0m $english_title"
        fi
        echo -e "\033[1mType:\033[0m $(echo $anime \
            | sed -nE 's|.*"mediaTypes":\[\{"name":"([^"]*)".*|\1 |p')"
        echo -e "\033[1mEpisode:\033[0m $(echo $anime \
            | sed -nE 's|.*"episodeNumber":([^,]*)(,"episodes":)?([^,]*)?,.*|\1/\3?|p' \
            | sed -nE 's/^(.*)((\/\?)|([0-9])\?)$/\1\3\4/p')"
        last_time=$ep_time
    done
    printf "\n"
    exit 0
}

recover_secrets() {
    secrets=$(echo .secrets)
    cli_id=$(cat $secrets | sed -nE 's|^([^,]*),.*$|\1|p')
    cli_secret=$(cat  $secrets | sed -nE 's|^[^,]*,(.*)$|\1|p')
}

get_mal_token() {
    challenger=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 128)
    
    : >$tmp_redir
    #-d $wwwdir && rm -rf $www_dir
    mkdir -p $www_dir
    printf "<html>\n<body>\n<h1>Verification Succeeded!</h1>\n<p>Close this browser tab and return to the shell.</p>\n</body>\n</html>\n" >"${www_dir}"/index.html
    trap "rm -rf $www_dir" EXIT
    python3 -m http.server -d $www_dir $redir_port >$tmp_redir 2>&1 &
    wserver_pid="$!"
    firefox "$mal_auth/authorize?response_type=code&client_id=$cli_id&code_challenge=$challenger" >/dev/null 2>&1
    printf "Please verify in Firefox\n"
    (
        sleep 120
        echo "timeout reached" >&2
        exit 1
    ) &
    read -r _
    kill "$!" >/dev/null 2>&1 || true
    unset _
    kill $wserver_pid
    echo $(grep GET $tmp_redir)
}

printf "\033[0m\n"

work_dir="${XDG_STATE_HOME:-$HOME/.local/state}/aniwatcher"
www_dir="${work_dir}/tmp-www"
tmp_redir="${work_dir}/redirectoutput"
redir_port="8080"
cli_id=""
cli_secret=""
challenger=""
mal_auth=""
mal_token=""
mal_auth="https://myanimelist.net/v1/oauth2"
mal_api="https://api.myanimelist.net/v2"

#recover_secrets
#get_mal_token

dep_ch "fzf" || true
get_schedule $(echo \
    "$(for i in {0..21}; do
        if [ $i -eq 7 ]; then
            printf "$i Today\n"
        else
            printf "$(date --date="-1 week + $i days" "+$i %a %e %b")\n"
        fi
    done)" \
    | fzf --with-nth=2.. --accept-nth=1 --reverse --cycle --bind 'load:pos(8)' --prompt "Select a day: ")

