#!/bin/sh

dep_ch() {
    for dep; do
        command -v "${dep%% *}" >/dev/null || die "Program \"${dep%% *}\" not found. Please install it."
    done
}

launcher() {
    [ -z "$1" ] && set -- "+m" "$2"
    fzf "$1" --with-nth=2.. --reverse --cycle --bind 'load:pos(8)' --prompt "$2"
}

nth() {
    stdin=$(cat -)
    [ -z "$stdin" ] && return 1
    line_count="$(printf "%s\n" "$stdin" | wc -l | tr -d "[:space:]")"
    [ "$line_count" -eq 1 ] && printf "%s" "$stdin" | cut -f2,3 && return 0
    prompt="$1"
    multi_flag=""
    [ $# -ne 1 ] && shift && multi_flag="$1"
    line=$(printf "%s" "$stdin" | cut -f1,3 | tr '\t' ' ' | launcher "$multi_flag" "$prompt" | cut -d " " -f 1)
    line_start=$(printf "%s" "$line" | head -n1)
    line_end=$(printf "%s" "$line" | tail -n1)
    [ -n "$line" ] || exit 1
    if [ "$line_start" = "$line_end" ]; then
        printf "%s" "$stdin" | grep -E '^'"${line}"'($|[[:space:]])' | cut -f2,3 || exit 1
    else
        printf "%s" "$stdin" | sed -n '/^'"${line_start}"'$/,/^'"${line_end}$"'/p' || exit 1
    fi
}

get_schedule() {
    today=$(date --date="-1 week + $1 days" '+%Y-%m-%d')
    this_year=$(date --date="-1 week + $1 days" '+%Y')
    this_week=$(date --date="-1 week + $1 days" '+%V')
    curr_time=$(date '+%H:%M')
    anisch_token="8oIOXRjBWyoDVdeIWhFkk4D7Clc5z9"
    animeschedule="https://animeschedule.net"
    printf "\033[96;1;4m\0Schedule for $(date --date="-1 week + $1 days" "+%A %e %B"):\033[0m\n"
    last_time=""
    curl -s -H "Authorization: Bearer $anisch_token" \
        "$animeschedule/api/v3/timetables/sub?year=$this_year&week=$this_week" \
        | sed 's|"title"|\n|g' | \
    while read -r anime; do
        # echo $anime
        if [ $today != $(echo $anime | sed -E 's|.*"episodeDate":"([^T]*)T.*|\1|1') ]; then
            continue
        fi
        ep_time=$(echo $anime \
            | sed -E 's|.*"episodeDate":"[^T]*T([^Z]*):[^:Z]*Z.*|\1|1')
        if [[ ! -z $last_time && $ep_time = $last_time ]]; then
            printf "\033[1m-------------\033[0m\n"
        else
            printf "\n\033[1m--- \033[%sm%s\033[39m ---\033[0m\n" \
                $(if [ $1 -gt 7 -o $curr_time \< $ep_time -a $1 -ge 7 ]; then
                    echo 33; else echo 32
                fi) \
                $ep_time
        fi
        echo -e "\033[1mTitle:\033[0m \033]8;;https://unix.stackexchange.com/questions/284476/terminal-create-hyperlinks\e\\$(echo $anime \
            | sed -nE 's|^:"([^"]*)",.*|\1|p')\033]8;;\033\\"
        english_title=$(echo $anime \
            | sed -nE 's|.*,"english":"([^"]*)",.*|\1|p')
        if [[ ! -z $english_title ]]; then
            echo -e "\033[1mEnglish Title:\033[0m $english_title"
        fi
        echo -e "\033[1mType:\033[0m $(echo $anime \
            | sed -nE 's|.*"mediaTypes":\[\{"name":"([^"]*)".*|\1 |p')"
        echo -e "\033[1mEpisode:\033[0m $(echo $anime \
            | sed -nE 's|.*"episodeNumber":([^,]*)(,"episodes":)?([^,]*)?,.*|\1/\3?|p' \
            | sed -nE 's/^(.*)((\/\?)|([0-9])\?)$/\1\3\4/p')"
        last_time=$ep_time
    done
    printf "\n"
    exit 0
}

printf "\033[0m\n"

dep_ch "fzf" || true
get_schedule $(echo \
    "$(for i in {0..21}; do
        if [ $i -eq 7 ]; then
            printf "$i Today\n"
        else
            printf "$(date --date="-1 week + $i days" "+$i %a %e %b")\n"
        fi
    done)" \
    | fzf --with-nth=2.. --accept-nth=1 --reverse --cycle --bind 'load:pos(8)' --prompt "Select a day: ")

